[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_anchor = "C2FPjy68iGyok4Psd9iB8BXANV4mFyZvvbjp8ReNny2g"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/efe/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
